modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0"

[[mods]]
modId = "gutils"
version = "${version}"
displayName = "General Utilities"
# displayURL="https://changeme.dev/"
logoFile="icon.png"
authors="FooterMan"
description = '''
Includes useful commands for Mod/ModPack Developers.
'''
[[dependencies.gutils]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
