modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "gutils"
version = "${mod_version}"
displayName = "${mod_name}"
# displayURL="https://changeme.dev/"
logoFile = "icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''


[[dependencies.gutils]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
