package dev.footer.gutils.lib;

import dev.footer.gutils.GeneralUtilities;
import net.neoforged.neoforge.common.ModConfigSpec;
import org.apache.commons.lang3.tuple.Pair;

public class ClientConfig {

    public final ModConfigSpec.BooleanValue export;


    ClientConfig(ModConfigSpec.Builder builder) {
        export = builder
                .translation(GeneralUtilities.ID + "export")
                .comment("Allows GUtils to export files generated by commands.")
                .define("export", false)
                ;

    }

    public static final ModConfigSpec config;
    public static final ClientConfig clientConfig;

    static {
        final Pair<ClientConfig, ModConfigSpec> pair = new ModConfigSpec.Builder()
                .configure(ClientConfig::new);
        config = pair.getRight();
        clientConfig = pair.getLeft();
    }
}
