name: Feature Request
about: Suggest a new feature for General Utilities
title: ''
labels: 'enhancement'
assignees: ''

---

**Feature Description**
A clear and concise description of the feature you're requesting.

**Why is this feature needed?**
Explain why you think this feature would be beneficial to the mod.

**Additional context**
Add any other context or screenshots about the feature request here.
