name: Feature Request
description: Request new features for General Utilities
labels: ["Enhancement"]
title: "[Suggestion] - "
body:
  - type: textarea
    attributes:
      label: Description
      description: "A clear and concise description of the feature you're requesting."
    validations:
      required: true
  - type: input
    attributes:
      label: Why is this feature needed?
      description: Explain why you think this feature would be beneficial to the mod.
    validations:
      required: true
  - type: input
    attributes:
      label: Additional Context
      description: Add any other context, such as screenshots, about the feature request here.
